#!/usr/bin/php
<?php

/**
* WizyTówka 5
* This script prepares "code/data" directory for developing purposes.
*/
namespace WizyTowka\Tools;
use WizyTowka as __;


include __DIR__ . '/../code/config.php';
include __\SYSTEM_DIR . '/init.php';


// Remove current "data" directory.
if (file_exists(__\DATA_DIR)) {
	$oldDataDir = __\DATA_DIR . '_' . date('Y-m-d') . '_' . time();

	rename(__\DATA_DIR, $oldDataDir);
	system('gio trash ' . $oldDataDir);
}

// Prepare settings.
$settings = [
	'websiteAddress'      => 'http://wizytowka.localhost',
	'websiteEmailAddress' => 'kontakt@wizytowka.localhost',
	'websiteTitle'        => 'Przykładowa witryna',
	'websiteTitlePattern' => '%s — Przykładowa witryna',
	'systemShowErrors'    => true,
];

if (empty($argv[1]) or $argv[1] == 'sqlite') {
	$settings['databaseType'] = 'sqlite';
}
elseif ($argv[1] == 'mysql' or $argv[1] == 'pgsql') {
	$settings['databaseType']     = $argv[1];
	$settings['databaseName']     = 'wizytowka';
	$settings['databaseHost']     = 'localhost';
	$settings['databaseUsername'] = 'wizytowka';
	$settings['databasePassword'] = '';
}
else {
	die('Wrong database type!' . PHP_EOL);
}

// Clean up current database (if exists) and create new.
if ($settings['databaseType'] == 'mysql') {
	system('mysql -u ' . $settings['databaseUsername'] . ' -e "DROP DATABASE IF EXISTS ' . $settings['databaseName'] . '"');
	system('mysql -u ' . $settings['databaseUsername'] . ' -e "CREATE DATABASE '         . $settings['databaseName'] . '"');
}
if ($settings['databaseType'] == 'pgsql') {
	system('dropdb --if-exists ' . $settings['databaseName'] . ' -U ' . $settings['databaseUsername']);
	system('createdb ' .           $settings['databaseName'] . ' -U ' . $settings['databaseUsername']);
}

// Install.
$installer = new __\_Private\Installer;

$installer->setUser('user_1', 'user_1');
$installer->appendSettings($settings);

$installer->install();


// Additional example data: users.
foreach (range(2, 3) as $number) {
	$user = new __\User;

	$user->name        = 'user_' . $number;
	$user->permissions = ($number == 2) ? __\User::PERM_MANAGE_PAGES : __\User::PERM_CREATE_PAGES;
	$user->setPassword($user->name);

	$user->save();
}

// Additional example data: pages.
foreach (range(1, 5) as $number) {
	$page = new __\Page;

	$page->slug    = 'przykladowa-strona-' . $number;
	$page->title   = 'Przykładowa strona #' . $number;
	$page->isDraft = !($number % 2);
	$page->noIndex = false;
	$page->userId  = 1;

	$page->contentType    = 'PlainText';
	$page->contents->html = '';

	$page->save();
}